# Generated by Django 5.0.6 on 2024-06-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdmnNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence', models.CharField(max_length=20, null=True)),
                ('mock', models.CharField(max_length=10, null=True)),
                ('test', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stdno', models.IntegerField(primary_key=True, serialize=False)),
                ('StdName', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('DOJ', models.DateField(null=True)),
                ('batch', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('performance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminstaff.attendence')),
            ],
        ),
    ]
