# Generated by Django 5.0.6 on 2024-06-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='rollnum',
            field=models.IntegerField(null=True),
        ),
    ]
