# Generated by Django 5.0.6 on 2024-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstaff', '0002_attendence_rollnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
