# Generated by Django 5.0.6 on 2024-06-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstaff', '0003_attendence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='casestudy',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
