# Generated by Django 5.0.6 on 2024-06-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstaff', '0004_attendence_casestudy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='performance',
        ),
    ]
