# Generated by Django 5.0.6 on 2024-07-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstaff', '0005_remove_students_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stdinfo',
            fields=[
            ],
            options={
                'ordering': ['stdno'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('adminstaff.students',),
        ),
    ]
