# Generated by Django 5.0.6 on 2024-07-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstaff', '0007_students_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phno',
            field=models.BigIntegerField(null=True),
        ),
    ]
